### PR TITLE
Raspberry Pi support

### PR DESCRIPTION
**Pull request by techyian**
This is linked to https://github.com/etlegacy/etlegacy/issues/885. Previous CMake options no longer required. Updated to disable XInput which causes mouse warping issue.

### CODE REVIEW

**Comment by rmarquis** [comment]
Since `-DVIDEO_X11_XINPUT=OFF` is virtually the only difference between the ARM and non=ARM unix variant, I was wondering if we could simplify the code further and apply the change in all situation.

And indeed, adding this flag actually fixes my issue on Linux under WSL - so I'll just go ahead and add that flag for everybody. We'll figure out if something breaks with feedback.

**Comment by rmarquis** [comment]
The other difference is that the non-ARM version uses `BUILD_BYPRODUCTS ${SDL32_BUNDLED_LIBRARIES}`. Does the code compile fine on your RPi with this extra flag?

**Comment by techyian** [comment]
Yes it seems to compile. Tested on the Pi 4 with GLES and it still runs correctly. I wasn't sure if there would be any negatives to having the extra flag there but I agree the two variations are so similar it makes sense to clean it up. I've committed the changes now.

**Comment by rmarquis** [comment]
Thanks! Rebased/squashed/merged!

**Pull request closed without merging**
