### PR TITLE
libs: updated to the latest libs

### PR DESCRIPTION
**Pull request by saukko28**
Updated and tested that everything functions just fine.

### CODE REVIEW

**Comment by rmarquis** [comment]
Thanks! However, from experience, libs update is usually risky and painful. Did you test compilation on windows/MSVC, windows/mingw and linux/gcc?

Especially, libjpeg-turbo is a risky update (from 1.3 -> 2.0). More than a simple drop-in of the code required, did you adjust the config files too?

Also, you'll have to push the SDL2 fix upstream. It's useless to fix it here (also, I don't have the issue you seem to mention on windows either).

**Comment by saukko28** [comment]
I compiled win/MSVC. I tried out and adjusted the config files accordingly.

I checked a bit how they have been adjusted before. Indeed others were updated without any pain. But indeed I can revert jpeg-turbo one because it actually required some tuning.

I can show soon how my fix affects.

**Comment by rmarquis** [comment]
All right, but I won't merge the whole before everything is correctly tested (I broke too many thing in the past).
The SQLite and Jansson update should be relatively safe though. FreeType is 50/50, curl and libjpeg are more often problematic.

**Comment by saukko28** [comment]
Alright! Merge all those you see fit. I'll look on the fixes later on.

**Comment by rmarquis** [comment]
Closing (the "fixes" aren't needed, curl is already obsolete). I pushed the SQLite and Jansson update. Freetype needs to be check on all platforms.

**Comment by saukko28** [comment]
I personally prefer building with MSVC. I thought it would be appropriate as a fix. I think it should be reconsidered at least. If it's not applied, I can still apply it locally, that's not a problem.

Thank you for the merge!

**Comment by rmarquis** [comment]
My mistake, I missed that one fix. Can you confirm it works for release as well as debug build on your side (with nmake)?

**Comment by saukko28** [comment]
I'll try later on when I'm able to!

**Pull request closed without merging**
